// PUZZLES
export const PUZZLES_LOADED = 'PUZZLES_LOADED';
export const FILTER_PUZZLES = 'FILTER_PUZZLES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const PUZZLE_SELECT = 'PUZZLE_SELECT';
export const CLEAR_SELECTED_PUZZLE = 'CLEAR_SELECTED_PUZZLE';
export const CLEAR_PUZZLES = 'CLEAR_PUZZLES';

// ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ERROR = 'ERROR';
